version: "3"

tasks:
  build:
    desc: Build the app
    cmds:
      - go build -o bin/gopher-cli main.go

  run:
    desc: Run the app
    cmds:
      - go run main.go

  install:
    desc: Install the app at $GOPATH
    cmds:
      - go install .

  clean:
    desc: Remove all retrieved *.png files
    cmds:
      - rm *.png
